/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.rekomendasi.gui;

import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.rekomendasi.type.Pengguna;

/**
 *
 * @author YuliArnezia
 */
public class PanelUtama extends javax.swing.JFrame 
{

    /**
     * Creates new form PanelUtama
     */
    private LoginForm loginJP;
    private Rekomendasi rekomendasiJP;
    private Pengguna pengguna;
    public PanelUtama() 
    {
        initComponents();
        loginJP = new LoginForm(this);
        rekomendasiJP = new Rekomendasi(this, pengguna);
        kembaliKeLoginAwal();
        this.setLocationRelativeTo(null);
    }
    
    public void kePanelRekomendasi()
    {
       
        myPanelUtama.removeAll();
        myPanelUtama.add(rekomendasiJP);
        myPanelUtama.repaint();
        myPanelUtama.revalidate();
        rekomendasiJP.setPengguna(pengguna);
        rekomendasiJP.inisialisasi();
        myPanelUtama.repaint();
        myPanelUtama.revalidate();
    }
    public void kembaliKeLoginAwal()
    {
        myPanelUtama.removeAll();
        myPanelUtama.add(loginJP);
        myPanelUtama.repaint();
        myPanelUtama.requestFocus();   
    }

    public Pengguna getPengguna() 
    {
        return pengguna;
    }

    public void setPengguna(Pengguna pengguna) 
    {
        this.pengguna = pengguna;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanelUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        myPanelUtama.setBackground(new java.awt.Color(255, 255, 255));
        myPanelUtama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        myPanelUtama.setMaximumSize(new java.awt.Dimension(1024, 668));
        myPanelUtama.setMinimumSize(new java.awt.Dimension(1024, 668));
        myPanelUtama.setPreferredSize(new java.awt.Dimension(1024, 668));
        myPanelUtama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                myPanelUtamaKeyPressed(evt);
            }
        });
        myPanelUtama.setLayout(new java.awt.BorderLayout());
        getContentPane().add(myPanelUtama, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_formKeyPressed

    private void myPanelUtamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_myPanelUtamaKeyPressed
         if (evt.isControlDown() && evt.getKeyCode() == KeyEvent.VK_X)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_myPanelUtamaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {
            public void run() 
            {
                new PanelUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel myPanelUtama;
    // End of variables declaration//GEN-END:variables
}
